# Estudiantes {#Estudiantes}

Este capítulo presenta el consolidado de las principales características asociadas a la información estadística oficial de los estudiantes matriculados en pregrado en la sede La Paz de la Universidad Nacional de Colombia. A continuación, se presenta una breve descripción de las secciones que hacen parte de este capítulo así como la ubicación del sitio web en donde se presentan las definiciones, los estándares y las codificaciones/clasificaciones que hacen parte de la información acá contenida (*metadatos*) y cuya exploración y lectura, sin duda, facilitará el entendimiento de las cifras asociadas a las poblaciones de estudiantes matriculados. 

La Sede La Paz en la actualidad no cuenta con programas de postgrado. Por lo anterior, en este capítulo no se dispone información estadística para este nivel de formación.

<h3>**Secciones**</h3> 


El proceso de formación en pregrado en la Sede La Paz se da a la luz de los lineamientos definidos en el Programa Especial de Admisión de esta sede creado mediante el [Acuerdo 301](http://www.legal.unal.edu.co/rlunal/home/doc.jsp?d_i=93599) de 2019 del CSU. Teniendo en cuenta lo anterior, en este capítulo se presentan las estadísticas oficiales asociadas a la población de estudiantes matriculados en pregrado en la Sede La Paz de la Universidad Nacional de Colombia.  

* [Matriculados en pregrado](#MatPre): contiene la información oficial del total de estudiantes matricualdos en pregrado en la Universidad y que han sido admitidos a través de la Sede La Paz. 


<h3>**Metadatos**</h3>

La construcción de las cifras oficiales de estudiantes matriculados en pregrado de la Sede La Paz, las definiciones que hacen parte de estas así como las codificaciones y clasificaciones aquí empleadas se encuentran contenidas en la sección **Matriculados** del capítulo de *Metadatos* de las cifras oficiales generales que hacen parte de la página de [estadísticas](http://estadisticas.unal.edu.co/home/) de la Universidad Nacional de Colombia. Invitamos a los lectores a explorar y conocer estos metadatos los cuales, además de orientar y facilitar el entendimiento de la información acá expuesta, se encuentran disponibles en el siguiente enlace.

* [Metadatos Cifras Oficiales Universidad Nacional de Colombia](http://estadisticas.unal.edu.co/menu-principal/cifras-generales/metadatos/cifras-generales/)

## Matriculados en pregrado{#MatPre}

A continuación, se presenta la información oficial del total de estudiantes matricualdos en pregrado en la Universidad y que han sido admitidos a través de la **Sede La Paz**. En específico, se presenta la evolución histórica de los matriculados en pregrado desde diferentes perspectivas: general, etapa de formación, sedes andinas, sexo, grupos de edad,  estrato socioeconómico, departamentos y municipios de residencia y programas académicos en los que estos se encuentran matriculados. Para cada una de las variables analizadas se presenta la evolución histórica (*serie de tiempo*) así como el comportamiento actual (*estado actual*) derivado de las últimas mediciones disponibles.

<!-- ### Evolución histórica -->

<!-- A continuación, la Figura \@ref(fig:F1MatPre), presenta la evolución histórica -*desde el periodo 20151*-, del total de matriculados en pregrado en la **Sede La Paz**. -->

<!-- ```{r F1MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- SERIE_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->


<!-- ### Información por etapa de formación  -->

<!-- A continuación, las figuras \@ref(fig:F2MatPre) y \@ref(fig:F3MatPre) presentan, respectivamente, la evolución histórica y el comportamiento actual del total de matriculados en pregrado en la **Sede La Paz** según la etapa de formación en la que estos se encuentran.  -->

<!-- * *Etapa Inicial*: Estudiantes matriculados en pregrado ubicados físicamente en la *Sede La Paz* -->

<!-- * *Etapa de movilidad*: Estudiantes matriculados en pregrado ubicados físicamente en las sedes andinas (*Bogotá*, *Medellín*, *Manizales* o *Palmira*). -->

<!-- <br> -->

<!-- ```{r F2MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- MOV_PEAMA_SERIE_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->

<!-- ```{r F3MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- MOV_PEAMA_ACTUAL_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->

<!-- ### Información por sede andina -->

<!-- A continuación, las figuras \@ref(fig:F4MatPre) y \@ref(fig:F5MatPre) presentan, respectivamente, la evolución histórica y el comportamiento actual del total de estudiantes matriculados de pregrado en la **Sede La Paz** según la sede andina en la que estos cursarán (etapa inicial) o se encuentran cursando sus estudios (etapa de movilidad). -->

<!-- ```{r F4MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- SEDE_ANDINA_SERIE_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->

<!-- ```{r F5MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- SEDE_ANDINA_ACTUAL_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->


<!-- ### Información por sexo  -->

<!-- A continuación, las figuras \@ref(fig:F6MatPre) y \@ref(fig:F7MatPre) presentan, respectivamente, la evolución histórica y el comportamiento actual del total de matriculados en pregrado en la **Sede La Paz** según el sexo biológico. -->

<!-- ```{r F6MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- SEXO_SERIE_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->

<!-- ```{r F7MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- SEXO_ACTUAL_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->

<!-- ### Información por edad -->

<!-- A continuación, las figuras \@ref(fig:F8MatPre) y \@ref(fig:F9MatPre) presentan, respectivamente, la evolución histórica y el comportamiento actual del total de estudiantes matriculados en pregrado de la **Sede La Paz** según grupos de edad. -->

<!-- ```{r F8MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- EDAD_SERIE_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->

<!-- ```{r F9MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- EDAD_ACTUAL_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->

<!-- ### Información por estrato -->

<!-- A continuación, las figuras \@ref(fig:F10MatPre) y \@ref(fig:F11MatPre) presentan, respectivamente, la evolución histórica y el comportamiento actual del total de estudiantes matriculados en pregrado en la **Sede La Paz** según el estrato socioeconómico. -->

<!-- ```{r F10MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- ESTRATO_SERIE_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->

<!-- ```{r F11MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- ESTRATO_ACTUAL_MAT_PRE -->
<!-- ``` -->

<!-- <br> -->


<!-- ### Tablas cifras agregadas -->

<!-- A continuación se presentan, a través de tablas, los agregados/consolidados históricos del total de matriculados en pregrado de la **Sede La Paz** por departamentos y municipios de procedencia así como los programas académicos de pregrado que estos cursan en las sedes andinas de la Universidad (Bogotá, Medellín, Manizales y Palmira). -->

<!-- Los interesados en *imprimir*, *copiar* o *descargar* estas cifras, pueden hacerlo a través de las múltiples opciones que se ofrecen en la parte superior izquierda de cada una de las tablas (Copiar, CSV, Excel, PDF e Imprimir). Así mismo, estas tablas permiten filtrar los resultados por aquellas variables de interés. -->


<!-- #### Departamentos y municipios de procedencia -->


<!-- A continuación, la Tabla \@ref(fig:F12MatPre) presenta los acumulados **históricos**, por **años y semestres**, en la **Sede La Paz**, de los matriculados en pregrado por departamentos y municipios de procedencia.  -->

<!-- ```{r F12MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- TABLA_MUNICIPIOS_MAT_PRE -->
<!-- ``` -->

<!-- #### Programas académicos de pregrado -->

<!-- A continuación, la Tabla \@ref(fig:F13MatPre) presenta el acumulado histórico de matriculados en pregrado, en la **Sede La Paz**, por años, semestres, sedes andinas, facultades y programas académicos cursados. -->

<!-- ```{r F13MatPre, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- TABLA_CARRERAS_ADM_PRE -->
<!-- ``` -->



<!-- ## Matriculados en postgrado {#MatPos} -->

<!-- A continuación, se presenta la información oficial del total de estudiantes matricualdos en postgrado en la Universidad y que han sido admitidos en la **Sede La Paz**. En específico, se presenta la evolución histórica de los **matriculados en postgrado** desde diferentes perspectivas: general, sexo, grupos de edad, departamentos y municipios de residencia y programas académicos en los que estos se encuentran matriculados. Para cada una de las variables analizadas se presenta la evolución histórica (*serie de tiempo*) así como el comportamiento actual (*estado actual*) derivado de las últimas mediciones disponibles. -->

<!-- ### Evolución histórica -->

<!-- A continuación, la Figura \@ref(fig:F1MatPos), presenta la evolución histórica -*desde el periodo 20091*-, del total de matriculados en postgrado en la **Sede La Paz**. -->

<!-- ```{r F1MatPos, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- SERIE_MAT_POS -->
<!-- ``` -->

<!-- <br> -->

<!-- ### Información por sexo  -->

<!-- A continuación, las figuras \@ref(fig:F2MatPos) y \@ref(fig:F3MatPos) presentan, respectivamente, la evolución histórica y el comportamiento actual del total de matriculados en postgrado en la **Sede La Paz** según el sexo biológico. -->

<!-- ```{r F2MatPos, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- SEXO_SERIE_MAT_POS -->
<!-- ``` -->

<!-- <br> -->

<!-- ```{r F3MatPos, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- SEXO_ACTUAL_MAT_POS -->
<!-- ``` -->

<!-- <br> -->

<!-- ### Información por edad -->

<!-- A continuación, las figuras \@ref(fig:F4MatPos) y \@ref(fig:F5MatPos) presentan, respectivamente, la evolución histórica y el comportamiento actual del total de estudiantes matriculados en postgrado de la **Sede La Paz** según grupos de edad. -->

<!-- ```{r F4MatPos, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- EDAD_SERIE_MAT_POS -->
<!-- ``` -->

<!-- <br> -->

<!-- ```{r F5MatPos, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- EDAD_ACTUAL_MAT_POS -->
<!-- ``` -->

<!-- <br> -->

<!-- ### Tablas cifras agregadas -->

<!-- A continuación se presentan, a través de tablas, los agregados/consolidados históricos del total de matriculados en postgrado de la **Sede La Paz** por departamentos y municipios de procedencia así como los niveles de formación y programas académicos de postgrado que estos cursan. -->

<!-- Los interesados en *imprimir*, *copiar* o *descargar* estas cifras, pueden hacerlo a través de las múltiples opciones que se ofrecen en la parte superior izquierda de cada una de las tablas (Copiar, CSV, Excel, PDF e Imprimir). Así mismo, estas tablas permiten filtrar los resultados por aquellas variables de interés. -->


<!-- #### Departamentos y municipios de procedencia -->


<!-- La Tabla \@ref(fig:F6MatPos) presenta los acumulados **históricos**, por **años y semestres**, en la **Sede La Paz**, de los matriculados en postgrado por departamentos y municipios de procedencia.  -->

<!-- ```{r F6MatPos, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- TABLA_MUNICIPIOS_MAT_POS -->
<!-- ``` -->

<!-- #### Programas académicos de postgrado -->

<!-- La Tabla \@ref(fig:F7MatPos) presenta el acumulado histórico de matriculados en postgrado, en la **Sede La Paz**, por años, semestres, niveles de formación y programas académicos cursados. -->

<!-- ```{r F7MatPos, fig.cap='Fuente: Dirección Nacional de Planeación y Estadística con base en información de la Dirección Nacional Información Académica'} -->
<!-- TABLA_CARRERAS_MAT_POS -->
<!-- ``` -->



